<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block Magmalabs\OrderSuccess\Block\Success */ ?>
<?php $order = $block->getOrder(); ?>
<?php $helper = $this->helper('Magmalabs\OrderSuccess\Helper\Data'); ?>

<div class="checkout-success">
    <div class="show-order">
        <table>
            <thead>
            <tr>
                <th colspan="2"><?php /* @escapeNotVerified */ echo __('Product Name'); ?></th>
                <th><?php /* @escapeNotVerified */ echo __('SKU'); ?></th>
                <th class="table-number"><?php /* @escapeNotVerified */ echo __('Price'); ?></th>
                <th class="table-number"><?php /* @escapeNotVerified */ echo __('Qty'); ?></th>
                <th class="table-number"><?php /* @escapeNotVerified */ echo __('Subtotal'); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($order->getAllVisibleItems() as $item) {
                $product = $helper->getProductById($item->getProductId());
                $options = $item->getProductOptions();
                $imageBlock = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct');
                $productImage = $imageBlock->getImage($product, 'category_page_list');
                ?>
                <tr class="data-item">
                    <td colspan="2">
                        <div class="product-image">
                            <a href="<?php echo $product->getProductUrl(); ?>"><?php echo $productImage->toHtml(); ?></a>
                        </div>
                        <h2 class="product-name"><span><?php echo $item->getName(); ?></span></h2>
                        <?php
                        if (!empty($options['attributes_info'])) {
                            foreach ($options['attributes_info'] as $option) {
                                ?>
                                <dl class="product-option">
                                    <dt class="option-label"><?php echo $option['label']; ?></dt>
                                    <dd class="option-value"><?php echo $option['value']; ?></dd>
                                </dl>
                                <?php
                            }
                        }
                        ?>
                    </td>
                    <td><?php echo $product->getSku(); ?></td>
                    <td class="table-number"><?php echo $helper->getFormatedPrice($item->getPrice()); ?></td>
                    <td class="table-number"><?php echo $item->getQtyOrdered(); ?></td>
                    <td class="table-number"><?php echo $helper->getFormatedPrice($item->getBaseRowTotal()); ?></td>
                </tr>
                <?php
            }
            ?>

            </tbody>
            <tfoot>
            <tr class="subtotal">
                <th colspan="5" class="table-method" scope="row">
                    <?php /* @escapeNotVerified */ echo __('Subtotal'); ?>
                </th>
                <td class="number" data-th="<?php /* @escapeNotVerified */ echo __('Subtotal'); ?>">
                    <span class="price"><?php echo $helper->getFormatedPrice($order->getSubtotal()); ?></span>
                </td>
            </tr>
            <tr class="shipping">
                <th colspan="5" class="table-method" scope="row">
                    <?php /* @escapeNotVerified */ echo __('Shipping &amp; Handling'); ?>
                </th>
                <td class="number" data-th="<?php /* @escapeNotVerified */ echo __('Shipping &amp; Handling'); ?>">
                    <span class="price"><?php echo $helper->getFormatedPrice($order->getShippingAmount()); ?></span>
                </td>
            </tr>
            <tr class="grand_total">
                <th colspan="5" class="table-method" scope="row">
                    <strong><?php /* @escapeNotVerified */ echo __('Grand Total'); ?></strong>
                </th>
                <td class="number" data-th="<?php /* @escapeNotVerified */ echo __('Grand Total'); ?>">
                    <strong><span class="price"><?php echo $helper->getFormatedPrice($order->getGrandTotal()); ?></span></strong>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>
</div>
